version: '3.8'

services:
  hassio-kohbo:
    build: .
    container_name: hassio-kohbo-app
    restart: unless-stopped
    ports:
      - "3001:80"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      # Home Assistant configuration - SET THESE ON YOUR VM
      - REACT_APP_HASS_URL=${REACT_APP_HASS_URL}
      - REACT_APP_HASS_TOKEN=${REACT_APP_HASS_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3